#!/usr/bin/python

#import myproject.myproject.wsgi

# reuse the application callable from myproject.wsgi
#application = myproject.myproject.wsgi.application

import os
import sys

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "myproject.settings")

if os.environ.has_key('OPENSHIFT_REPO_DIR'):
    sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi', 'myproject'))
    virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/'
    os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.7/site-packages')
    virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
    try:
        execfile(virtualenv, dict(__file__=virtualenv))
    except IOError:
        pass

from django.core.wsgi import get_wsgi_application
application = get_wsgi_application()